/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-08-30 12:44:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import project.ConnectionProvider;
import java.sql.*;

public final class addressPaymentForOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("project.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Payment Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/addresspayment.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"  />\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	if(window.history.forward(1)!=null)\r\n");
      out.write("		window.history.forward(1);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<table>\r\n");
      out.write("	<thead>\r\n");
      out.write("	");

		String email=session.getAttribute("email").toString();
		int total=0;
		int sno=0;
		String address="";
		String city="";
		String state="";
		String country="";
		try{ 
			Connection con=ConnectionProvider.getCon();
			Statement st=con.createStatement();
			ResultSet rs1=st.executeQuery("select sum(total) from cart where email='"+email+"' and address is NULL ");
			while(rs1.next())
			{
				total=rs1.getInt(1);
			}
	
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th><a href=\"mycart.jsp\" style=\"text-align:center;  margin-top:0px; color:black; cursor:pointer; magin-left:50px;text-decoration:none; font-size:27px\"><i class=\"fa-solid fa-backward\"></i>&nbsp;Back</a></th>\r\n");
      out.write("			<th style=\"background-color:black; color:white\">Total:");
out.println(total); 
      out.write("</th>\r\n");
      out.write("		</tr>	\r\n");
      out.write("	</thead>\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr >\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Sr.No</td>\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Product Name</td>\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Category</td>\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Price</td>\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Quantity</td>\r\n");
      out.write("			<td  style=\"background-color:lightblue;\">Sub Total</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody>\r\n");
      out.write("	");

			ResultSet rs=st.executeQuery("select * from product inner join cart on product.id=cart.product_id and cart.email='"+email+"' and cart.address is NULL ");
			while(rs.next()){
			
			
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("			");
sno=sno+1; 
      out.write("\r\n");
      out.write("			<td>");
out.println(sno); 
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(3) );
      out.write("</td>\r\n");
      out.write("			<td><i class=\"fa-solid fa-indian-rupee-sign\">&nbsp;</i>");
      out.print(rs.getString(4) );
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString(8) );
      out.write("</td>\r\n");
      out.write("			<td><i class=\"fa-solid fa-indian-rupee-sign\">&nbsp;</i>");
      out.print(rs.getString(10) );
      out.write("</td>\r\n");
      out.write("			\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		ResultSet rs2=st.executeQuery("select * from users where email='"+email+"' ");
		while(rs2.next()){		
			
		
      out.write("\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<hr>\r\n");
      out.write("<form action=\"addressPaymentForOrderAction.jsp\" method=\"post\">\r\n");
      out.write("	<div class=\"addbox\">\r\n");
      out.write("		<div class=\"addflex\">\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Enter Address</h1>\r\n");
      out.write("				<input type=\"text\" name=\"address\" placeholder=\"Enter Address\" value=\"");
      out.print(rs2.getString("address") );
      out.write("\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Enter City </h1>\r\n");
      out.write("				<input type=\"text\" name=\"city\" placeholder=\"Enter City\"  value=\"");
      out.print(rs2.getString("city") );
      out.write("\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"addflex\">\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Enter State</h1>\r\n");
      out.write("				<input type=\"text\" name=\"state\" placeholder=\"Enter State\" value=\"");
      out.print(rs2.getString("state") );
      out.write("\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Enter Country</h1>\r\n");
      out.write("				<input type=\"text\" name=\"country\" placeholder=\"Enter Country\" value=\"");
      out.print(rs2.getString("country") );
      out.write("\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<h3>If there is no address its means that you did not set you address! </h3>\r\n");
      out.write("		<h3>This address will also updated to your profile</h3>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"addbox\">\r\n");
      out.write("		<div class=\"addflex\">\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Select Way Of Payment</h1>\r\n");
      out.write("				<select name=\"paymentMethod\">\r\n");
      out.write("					<option value=\"Cash On Delivery\">Cash On Delivery</option>\r\n");
      out.write("					<option value=\"Online Payment\">Online Payment</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Pay online on this abc@ybl</h1>\r\n");
      out.write("				<input type=\"text\" name=\"transactionId\" placeholder=\"Enter transactionId\">\r\n");
      out.write("				<h3>If you select online payment then enter your transaction ID here otherwise leave this blank</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"addflex\">\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h1>Mobile Number</h1>\r\n");
      out.write("				<input type=\"number\" name=\"mobilenumber\" placeholder=\"Enter Mobile\" required>\r\n");
      out.write("				<h3>This mobile number will also updated to your profile</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"addflex1\">\r\n");
      out.write("				<h3 style=\"margin-top: 10rem;\">If you enter wrong transaction id then your order will we can cancel!</h3>\r\n");
      out.write("				<button type=\"submit\">Procced to Generate Bill & Save </button>\r\n");
      out.write("				<h3>Fill Form correctly</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");

		}
		}catch(Exception e){
			System.out.println(e);
		}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
