/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-09-03 06:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import project.ConnectionProvider;
import java.sql.*;

public final class changemobilenumber_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/changedetailsheader.jsp", Long.valueOf(1725042810996L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("project.ConnectionProvider");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" 	<title> Change Details  Header</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"CSS/adminHeader.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\"  />\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"abox\">\r\n");
      out.write("<h1 Style=\"text-align:center; margin-top:1rem;margin-bottom:1rem;color:red;\">Change Details</h1>\r\n");
 String email=session.getAttribute("email").toString(); 
      out.write("\r\n");
      out.write("<div class=\"aheader\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"nav\">\r\n");
      out.write("				<a href=\"header.jsp\">Back\r\n");
      out.write("				<i class=\"fa-solid fa-caret-left\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<a href=\"changedetails.jsp\">(");
out.println(email); 
      out.write(")\r\n");
      out.write("				<i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<a href=\"changepassword.jsp\">Change Password\r\n");
      out.write("				<i class=\"fa-solid fa-key\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<a href=\"addChangeAddress.jsp\">Add Or Change Address\r\n");
      out.write("				<i class=\"fa-solid fa-location-dot\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"nav\">\r\n");
      out.write("				<a href=\"changemobilenumber.jsp\">Change Mobile Number\r\n");
      out.write("				<i class=\"fa-solid fa-phone-flip\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	 \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Change Password</title>\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/changedetails.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    .mbox  .mbox1{\r\n");
      out.write("    width: 70%;\r\n");
      out.write("    height: 420px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 35%;\r\n");
      out.write("    left: 25%;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("	}\r\n");
      out.write("	.mbox .mbox1 .SignUp input{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    margin: 10px 10%;\r\n");
      out.write("    border-bottom: 2px solid black !important;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border: none;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

String msg=request.getParameter("msg");
if("done".equals(msg)){

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h3 style=\"margin-top:5.5rem;margin-left:30rem;font-size:30px;color:red;\" >Mobile Number Changed Successfully</h3>\r\n");
} 
      out.write('\r');
      out.write('\n');

if("wrong".equals(msg)){

      out.write("\r\n");
      out.write("<h3 style=\"margin-top:6.5rem;margin-left:38rem;font-size:30px;color:red;\">Your Password is Wrong</h3>\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"ChangeMobileNumberServlet\" method=\"post\">	\r\n");
      out.write("<div class=\"mbox\">\r\n");
      out.write("       <div class=\"mbox1\">\r\n");
      out.write("             <div class=\"SignUp\">\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Enter Your Phone Number\" required name=\"mobilenumber\" style=\"margin-top:2rem;\" required>                  \r\n");
      out.write("                	<input type=\"password\" placeholder=\"Enter Password(For Security)\" required name=\"password\" style=\"margin-top:2rem;\" required>                  \r\n");
      out.write("                	<input type=\"submit\" value=\"Save\" style=\"margin-left:7rem;border-radius:10px\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write(" </form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
